name: Test Cron Job
on:
  schedule:
    - cron: '0 */11 * * *'

jobs:
      test-cron-job:
        name: Test Cron Job Execution
        runs-on: ubuntu-latest
        steps:
            -run: echo "Cron job executed successfully!"
      

